services:
  redis:
    image: redis:latest
    container_name: url-shortener-redis
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-db-network
  postgres:
    image: postgres:18
    container_name: url-shortener-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-db-network 

  traefik:
    image: traefik:latest
    container_name: url-shortener-traefik
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-app-network
    restart: unless-stopped
    command: 
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    depends_on:
      - server
      
  server:
    image: blessseddd/url-shortener-server:latest
    container_name: url-shortener-server
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}  
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - proxy-app-network
      - app-db-network
    labels:
      - traefik.enable=true
      - "traefik.http.routers.server-url-shortener.rule=PathPrefix(`/`)"
      - "traefik.http.routers.server-url-shortener.entrypoints=web"
      - "traefik.http.services.server-url-shortener.loadbalancer.server.url=http://url-shortener-server.url-shortener_proxy-app-network:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
volumes:
  postgres_data:

networks:
  app-db-network:
    driver: bridge
  proxy-app-network:
    driver: bridge